[pytest]
addopts = --html=reports/report.html --self-contained-html
markers =
    registration: All registration tests
    positive: All positive path tests
    debug: Use only for one test at time to debug it. No extra reports etc.