[pytest]
addopts = --html=reports/report.html --self-contained-html -n auto
markers =
    registration: All registration tests
    login: All log in tests
    positive: All positive path tests
    negative: All negative path tests
    products: All tests with products pages
    debug: Use only for one test at time to debug it. No extra reports etc.